default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: event_manager_user
  password: event_manager_password
  host: localhost

development:
  <<: *default
  database: event_manager_db_development

test:
  <<: *default
  database: event_manager_db_test

production:
  <<: *default
  database: event_manager_db_production
  username: your_pg_username
  password: <%= ENV['YOUR_DATABASE_PASSWORD'] %>
